version: "3.8"

services:

  db:
    image: postgres:12.3-alpine
    container_name: postgres-oauth2
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks: 
      - "project-oauth"
    environment:
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_DB=db_project_oauth2
         - PGDATA=/var/lib/postgresql/data/pgdata

  app:
    image: mupezzuol/springboot-oauth2-rbac:latest
    container_name: app-oauth2
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks: 
      - "project-oauth"
    depends_on:
      - db

networks: 
  project-oauth:
